import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
const cssSource = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

test("sidebar switches between the five stage-map collections", () => {
  assert.match(pageSource, /switchView\("global"\)/);
  assert.match(pageSource, /switchView\("crypto7"\)/);
  assert.match(pageSource, /switchView\("usSelected"\)/);
  assert.match(pageSource, /switchView\("chinaIndices"\)/);
  assert.match(pageSource, /switchView\("hkSelected"\)/);
  assert.match(pageSource, /加密市场阶段地图/);
  assert.match(pageSource, /美股指数阶段地图/);
  assert.match(pageSource, /A股指数阶段地图/);
  assert.match(pageSource, /港股指数阶段地图/);
  assert.match(pageSource, /CRYPTO MARKEET STAGES/);
  assert.match(pageSource, /US INDEX STAGES/);
  assert.match(pageSource, /HONG KONG INDEX STAGES/);
  assert.match(pageSource, /"日股" \| "欧股"/);
  assert.match(pageSource, /GLOBAL INDEX STAGES MAP/);
  assert.match(pageSource, /全球指数趋势地图/);
  assert.match(pageSource, /全球主要市场趋势看版/);
  assert.match(pageSource, /global: \["GSPC\.INDEX", "NDQ", "SOXX", "VIX", "000300\.SH", "SZ399006", "HSI", "HSTECH", "N225", "STOXX50E", "DXY", "US10Y", "XAU", "CL", "BTC-USD", "ETH-USD"\]/);
  assert.match(pageSource, /crypto7: \["HOOD", "CRCL", "COIN", "MSTR", "BTC-USD", "ETH-USD", "SOL-USD", "HYPE-USD"\]/);
  assert.match(pageSource, /"SOL-USD": \{ shortCode: "SOL", cols: 3, rows: 2 \}/);
  assert.doesNotMatch(pageSource, /item\.code === "BTC-USD" \? 6/);
  assert.match(pageSource, /usSelected: \["GSPC\.INDEX", "NDQ", "RSP", "IWM", "VIX", "SOXX", "XLF", "XLE", "XLV", "XLI", "XLY", "NVDA", "MSFT", "AAPL", "AMZN", "TSLA", "BRK\.B", "WMT", "DXY", "US10Y"\]/);
  assert.match(pageSource, /label: "市场", className: "map-us-market"/);
  assert.match(pageSource, /label: "行业", className: "map-us-sector"/);
  assert.match(pageSource, /label: "核心资产", className: "map-us-leaders"/);
  assert.match(pageSource, /group="宏观" className="map-us-macro"/);
  assert.doesNotMatch(pageSource, /label: "(?:MARKET｜市场|SECTOR｜行业|LEADERS｜核心资产|INDEX|MEGA CAP|SECTOR)"/);
  assert.match(pageSource, /"BRK\.B": \{ shortCode: "BRK"/);
  assert.match(pageSource, /chinaIndices: \["000510\.SH", "000300\.SH", "000905\.SH", "000852\.SH", "000016\.SH", "SZ399006", "000688\.SH", "000985\.SH", "931865\.CSI", "930651\.CSI", "399975\.SZ", "399986\.SZ", "930708\.CSI", "399933\.SZ", "399997\.SZ", "930997\.CSI"\]/);
  assert.match(pageSource, /label: "市场", className: "map-china-market", codes: \["000510\.SH", "000300\.SH", "000905\.SH", "000852\.SH", "000016\.SH", "SZ399006", "000688\.SH", "000985\.SH"\]/);
  assert.match(pageSource, /label: "行业", className: "map-china-sector", codes: \["931865\.CSI", "930651\.CSI", "399975\.SZ", "399986\.SZ", "930708\.CSI", "399933\.SZ", "399997\.SZ", "930997\.CSI"\]/);
  assert.match(pageSource, /"931865\.CSI": \{ shortCode: "半导体"/);
  assert.match(pageSource, /"930651\.CSI": \{ shortCode: "计算机"/);
  assert.match(pageSource, /"930997\.CSI": \{ shortCode: "新能源车"/);
  assert.match(pageSource, /hkSelected: \["HSI", "HSTECH", "700\.HK", "9988\.HK", "5\.HK", "1299\.HK", "388\.HK", "939\.HK", "1810\.HK", "3690\.HK", "941\.HK", "883\.HK", "1211\.HK", "16\.HK", "2\.HK", "1093\.HK"\]/);
  assert.match(pageSource, /label: "指数", className: "map-hk-index", codes: \["HSI", "HSTECH"\]/);
  assert.match(pageSource, /label: "核心蓝筹", className: "map-hk-mega", codes: \["700\.HK", "9988\.HK", "5\.HK", "1299\.HK", "388\.HK", "939\.HK"\]/);
  assert.match(pageSource, /label: "行业代表", className: "map-hk-sector", codes: \["1810\.HK", "3690\.HK", "941\.HK", "883\.HK", "1211\.HK", "16\.HK", "2\.HK", "1093\.HK"\]/);
  assert.match(pageSource, /"5\.HK": \{ shortCode: "0005"/);
  assert.match(pageSource, /"388\.HK": \{ shortCode: "0388"/);
  assert.match(pageSource, /"16\.HK": \{ shortCode: "0016"/);
  assert.match(pageSource, /"2\.HK": \{ shortCode: "0002"/);
  assert.match(pageSource, /item\.collections\.includes\(view\)/);
  assert.match(cssSource, /\.view-crypto7 \.map-美股/);
  assert.match(pageSource, /crypto7: \{[^}]*groups: \["加密", "美股"\]/);
  assert.match(cssSource, /\.view-crypto7 \.map-加密 \{ grid-area: 1 \/ 1 \/ 9 \/ 7; \}/);
  assert.match(cssSource, /\.view-crypto7 \.map-美股 \{ grid-area: 1 \/ 7 \/ 9 \/ 13; \}/);
  assert.match(cssSource, /\.view-usSelected \.map-us-market \{ grid-area: 1 \/ 1 \/ 4 \/ 11; \}/);
  assert.match(cssSource, /\.view-usSelected \.map-us-sector \{ grid-area: 4 \/ 1 \/ 7 \/ 11; \}/);
  assert.match(cssSource, /\.view-usSelected \.map-us-leaders \{ grid-area: 7 \/ 1 \/ 10 \/ 11; \}/);
  assert.match(cssSource, /\.view-usSelected \.map-us-macro \{ grid-area: 1 \/ 11 \/ 10 \/ 13; \}/);
  assert.match(cssSource, /\.view-usSelected \.map-us-market \.map-tiles \{ grid-template-columns: repeat\(5,/);
  assert.match(cssSource, /\.view-usSelected \.map-us-sector \.map-tiles \{ grid-template-columns: repeat\(6,/);
  assert.match(cssSource, /\.view-usSelected \.map-us-leaders \.map-tiles \{ grid-template-columns: repeat\(7,/);
  assert.match(cssSource, /\.view-usSelected\.single-map \.map-大宗-宏观 \.map-tiles \{ grid-template-columns: repeat\(2,/);
  assert.match(cssSource, /\.view-chinaIndices \.map-china-market \{ grid-area: 1 \/ 1 \/ 5 \/ 13; \}/);
  assert.match(cssSource, /\.view-chinaIndices \.map-china-sector \{ grid-area: 5 \/ 1 \/ 9 \/ 13; \}/);
  assert.match(cssSource, /\.view-chinaIndices \.map-china-market \.map-tiles, \.view-chinaIndices \.map-china-sector \.map-tiles \{ grid-template-columns: repeat\(4,/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-index \{ grid-area: 1 \/ 1 \/ 3 \/ 13; \}/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-mega \{ grid-area: 3 \/ 1 \/ 6 \/ 13; \}/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-sector \{ grid-area: 6 \/ 1 \/ 9 \/ 13; \}/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-index \.map-tiles \{ grid-template-columns: repeat\(2,/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-mega \.map-tiles \{ grid-template-columns: repeat\(3,/);
  assert.match(cssSource, /\.view-hkSelected \.map-hk-sector \.map-tiles \{ grid-template-columns: repeat\(4,/);
  assert.match(pageSource, /className="distribution-fill"/);
  assert.match(pageSource, /color-mix\(in srgb, \$\{stageMeta\[stage\]\.color\} 14%, var\(--canvas\)\)/);
  assert.match(pageSource, /style=\{\{ width: `\$\{percent\}%`/);
  assert.match(cssSource, /\.distribution-segment \{[^}]*flex: 1 1 0;/);
  assert.match(cssSource, /\.distribution-fill \{[^}]*inset: 0 0 0 auto;/);
  assert.match(cssSource, /\.map-大宗-宏观 \{ grid-area: 5 \/ 1 \/ 9 \/ 5; \}/);
  assert.match(cssSource, /\.map-加密 \{ grid-area: 5 \/ 5 \/ 9 \/ 8; \}/);
  assert.match(cssSource, /\.map-日股 \{ grid-area: 5 \/ 8 \/ 9 \/ 10; \}/);
  assert.match(cssSource, /\.map-欧股 \{ grid-area: 5 \/ 10 \/ 9 \/ 13; \}/);
});
